# Generated by Django 3.1.3 on 2020-11-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productreview_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='review',
            new_name='rating',
        ),
    ]
