# Generated by Django 3.1.3 on 2020-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20201129_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(related_name='seller', to='ecommerce.Product'),
        ),
    ]
