# Generated by Django 3.1.3 on 2020-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20201129_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, to='ecommerce.Product'),
        ),
    ]
